### ISSUE TITLE
New Rate Limiting API

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#3335]
# Problem Summary
Gloo Enterprise currently exposes a fine-grained rate limit API that allows you to configure a [vast number of use cases](https://docs.solo.io/gloo/latest/guides/security/rate_limiting/envoy/).
The two main objects that make up the API are:
1. the [`descriptors`](https://docs.solo.io/gloo/latest/guides/security/rate_limiting/envoy/#descriptors), which configure the rate limit server and are defined on the global `Settings` resource, and
2. the [`actions`](https://docs.solo.io/gloo/latest/guides/security/rate_limiting/envoy/#actions) that determine how Envoy composes the descriptors that are sent to the server to check whether a request should be rate-limited; `actions` are defined either on the `Route` or on the `VirtualHost` `options`.
  
Although powerful, this API has some drawbacks:
- The `descriptors` that define the rate limit policies you want to enforce are defined in a single, central location. 
  The global nature of the `Settings` does not guarantee isolation between different rate limits: if you make a mistake 
  while updating a policy, you might end up impacting other policies. This centralized configuration also makes it 
  harder to safely manage you rate limit policies in an automated fashion.
- Since `actions` are defined directly on your `Virtual Services`, your rate limits are tightly coupled to your routing 
  configuration. If you need to apply the same policy on different routes, you will need to redefine the same 
  configuration in multiple places. This can be a significant source of configuration bloat, especially if your policies 
  are complex.

# Proposed solution
To address these shortcomings, we will introduce a new `RateLimitConfig` custom resource. A `RateLimitConfig` resource represents a self-contained rate limit policy; this means that Gloo will use the resource to configure both the Envoy proxies and the Gloo Enterprise rate limit server they communicate with. Gloo will guarantee that rate limit rules defined on different `RateLimitConfig` resources are completely independent of each other.

Here is a simple example of a `RateLimitConfig` resource:

```yaml
apiVersion: ratelimit.solo.io/v1alpha1
kind: RateLimitConfig
metadata:
  name: my-rate-limit-policy
  namespace: gloo-system
spec:
  raw:
    descriptors:
    - key: generic_key
      value: counter
      rateLimit:
        requestsPerUnit: 10
        unit: MINUTE
    rateLimits:
    - actions:
      - genericKey:
          descriptorValue: counters
```

Once an `RateLimitConfig` is created, it can be used to enforce rate limits on your `Virtual Services` (or on the 
lower-level `Proxy` resources) by simply referencing it on `VirtualHosts` and `Routes`.

```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: example
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - '*'
    options:
      rateLimitConfigs:
        refs:
        - name: my-rate-limit-policy
          namespace: gloo-system
    routes:
      - matchers:
        - prefix: /foo
        routeAction:
          single:
            upstream:
              name: example-upstream
              namespace: gloo-system
      - matchers:
        - prefix: /
        options:
          rateLimitConfigs:
            refs:
            - name: my-other-policy
              namespace: gloo-system
        routeAction:
          single:
            upstream:
              name: other
              namespace: gloo-system
```

# Task checklist
- [x] Update the Rate Limit API definitions in the open source Gloo repository
- [x] Update the Gloo Enterprise Rate Limit server to handle the new configuration format
- [ ] Update the Gloo Enterprise control plane so it can process the `RateLimitConfig` resource
- [x] Update the rate limit documentation
