### ISSUE TITLE
Refresh grant to extend the session, given a minimum TTL threshold

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4447]
Gloo refreshes the `id_token` when it is expired. 
If I want to prevent edge cases where the `id_token` is about to expire (say, in the next 10ms), and the backend actually receives an expired token. 
Can I prevent that with a threshold, like a minimum acceptable TTL, that will trigger the refresh grant?

**Comment by sam-heilbron** [comment]
During OIDC, if the jwt is expired, we execute a refresh flow: https://github.com/solo-io/ext-auth-service/blob/6b82e1ddfb89107e48c365255f81e74cedf9d90c/pkg/config/oidc/oidc_request.go#L450

However, if the jwt is not yet expired, it is accepted and the request is sent upstream. If that upstream validates the token separately, it will validate that token, which is now expired. The effect is that the request is denied, even though there is a valid token. 

The ask is to provide a buffer to the jwt expiry, so instead of refreshing after it is expired, refresh after expiry_time-buffer. 

The oidc refresh flow: https://github.com/solo-io/ext-auth-service/blob/6b82e1ddfb89107e48c365255f81e74cedf9d90c/pkg/config/oidc/oidc_request.go#L450

which is triggered after the token claims are parsed: https://github.com/solo-io/ext-auth-service/blob/6b82e1ddfb89107e48c365255f81e74cedf9d90c/pkg/config/oidc/oidc_request.go#L390

we could probably rely on the `VerifyExpiresAt` exposed on the MapClaims here: https://github.com/dgrijalva/jwt-go/blob/9742bd7fca1c67ba2eb793750f56ee3094d1b04f/map_claims.go#L36

**Comment by sam-heilbron** [comment]
Should the buffer be hardcoded or configurable? Perhaps configurable but with a sane default (2s)

@chrisgaun why do we need this feature in the first place?

**Comment by marcelsigner** [comment]
There are several reasons for the request:

- first of all every backend must repeat the access control because backends also call each other because we have applied a zero-trust policy inside the cluster. Backends do a much more fine-grained access control. In Gloo Edge we only do a coarse grained access control.
- even if the access token is still valid when backend A receives the request, the access_token may expire when backend A calls backend B.
- in some cases backend A has to exchange the token to call backend B. The OAuth Server rejects the token_exchange if the token is already expired. Reasons for the token_exchange:
       - in some cases backend A sends an asynchronous message to backend B passing the access_token in the message header.
         Messages are queued and the access_token needs an extended expiration.
      - The access_token belonging to the gloo-session does not have sufficient scope to call backend b.
         A token_exchange from a different OAuth client can extend scopes. 

We really appreciate the implementation of a configurable threshold. 2s is a perfect default!
Thanks a lot!

**Comment by chrisgaun** [comment]
They will likely want this to be backported

**Comment by MitchAman** [comment]
> They will likely want this to be backported 

To what version?

**Comment by marcelsigner** [comment]
Yes please, we would very much appreciate it. We currently run 1.9.1.

**Comment by chrisgaun** [comment]
Looks like you got your ans

**Comment by MitchAman** [comment]
Status:

- PRs:
    - [x] Gloo API change: https://github.com/solo-io/gloo/pull/5616
    - [x] solo-apis, exposing the gloo API change: https://github.com/solo-io/solo-apis/pull/267
    - [ ] ext-auth-service implementation: https://github.com/solo-io/ext-auth-service/pull/275
    - [ ] solo-projects: https://github.com/solo-io/solo-projects/pull/2890
- 1.9.x Backport PRs:
    - [ ] gloo: // TODO
    - [ ] solo-apis: // TODO
    - [ ] ext-auth-service: // TODO
    - [ ] solo-projects: // TODO

**Comment by sam-heilbron** [comment]
Re-opening for 1.9 backports

**Comment by MitchAman** [comment]
Closing as 1.9.x backports have been released.
