### ISSUE TITLE
Trace and Span IDs are coming as null if the message is a direct response action, or a transformation

### ISSUE THREAD

**Issue by chrisgaun** [solo-io/gloo#5368]
Outcome: Identify why this is occurring. If this is something we can resolve in a day or two, do it, otherwise write up an issue outlining the change required.

**Comment by chrisgaun** [comment]
@bcollard was looking into this and there is more information in Zendesk

**Comment by MitchAman** [comment]
@chrisgaun What value is the customer trying to get from tracing direct response actions?

**Comment by bcollard** [comment]
@asayah FYI

**Comment by sam-heilbron** [comment]
Remaining work:
- [ ] Update external facing docs (@bewebi )
- [ ] Update README to outline how to setup tracing (@MitchAman )
- [ ] Try to use transformation to achieve this (@sam-heilbron )

**Comment by sam-heilbron** [comment]
## Tracing and Direct Response Action in Envoy

Tracing docs: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/tracing#arch-overview-tracing
 
Tracing is implemented in the HttpConnectionManager (HCM): https://github.com/envoyproxy/envoy/blob/f393ff14d4dd07650c4090138430b711396ba27a/source/common/http/conn_manager_impl.cc#L714
 
Direct Response Action is available both as a Network Filter (https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/direct_response_filter#config-network-filters-direct-response) and an HttpFilter (https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_routing.html?highlight=direct%20response#arch-overview-http-routing-direct-response). In Gloo, we expose Direct Response Action's as Route configuration (https://github.com/solo-io/gloo/blob/cfa3c17ab2552a594966da9aaad3f7c8b9678b7c/projects/gloo/api/external/envoy/api/v2/route/route.proto#L174) on a VirtualService or RouteTable, meaning that we rely on the HttpFilter.
 

## Access Logs
The provided Zendesk ticket relied on Access Logs configured with:
```
options:
	accessLoggingService:
  	accessLog:
  	- fileSink:
      	jsonFormat:
        	durationInMillis: '%DURATION%'
        	operation: '%REQ(:METHOD)%'
        	parentSpanId: '%REQ(x-b3-parentspanid)%'
        	spanId: '%REQ(x-b3-spanid)%'
        	traceId: '%REQ(X-B3-Traceid)%'
 timestamp: '%START_TIME%'
            type: span
      	path: /dev/stdout
 
```
 
This means that the request headers are used to populate the access logs.

## How are request headers modified?
 
As Envoy docs point out (https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/tracing#arch-overview-tracing), these headers are used to propagate trace context between services.
 
Since the Router filter is the last filter in the Http FilterChain, I would have expected the headers to be added to the request before we process the Router filter (and thus the DirectResponseAction).
 
However, looking more closely at the Envoy code, it's clear that headers are never meant to be added to the request for DirectResponseActions:
 
The router determines if a route uses a DRA: https://github.com/envoyproxy/envoy/blob/f393ff14d4dd07650c4090138430b711396ba27a/source/common/router/router.cc#L399
 
Later in the function do we inject headers for non-direct response actions: https://github.com/envoyproxy/envoy/blob/5b1015cffbf6e02a7ccec9c12a6b7f246f8f3d30/source/common/router/router.cc#L646
 
Specifically the Zipkin implementation:
https://github.com/envoyproxy/envoy/blob/db74e313b3651588e59c671af45077714ac32cef/source/extensions/tracers/zipkin/zipkin_tracer_impl.cc#L42
 

## Outcome 
This means that if a request is handled by a DirectResponseAction, it will never reach the line of code responsible for modifying request headers to include the span context. This is because the request will never be handled by an external service (and instead we just send a local reply), so there is no need to modify the request.
 
There are 2 options where this situation occurs:
1. Originating client sends relevant b3 headers. _In this instance the headers are passed through via the request and they show up in the access logs_
2. Originating client does not send the relevant b3 headers. _This is the instance we describe above, and headers are never modified because they aren't sent to any external service. Even if we were to include a span ID and trace ID, these values would be meaningless because they're just a unique identifier._
 
cc @bewebi @MitchAman

**Comment by MitchAman** [comment]
Reopened as https://github.com/solo-io/gloo/pull/5545 didn't actually resolve this, it only added to the tracing documentation.
