### ISSUE TITLE
Support K8s 1.26

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#8164]
### Describe the requested changes
Add support for k8s 1.26 in Gloo Edge.

### Tasks
Each of these tasks can be accomplished discretely:
- [ ] Today we use k8s 1.25 libraries in edge 1.14 this does not mean that 1.26 wont work but rather we should figure out what features if any wouldnt work today with k8s 1.26. Use CI and local runs to determine if tests can run using kube 1.26 on edge 1.14. Document your findings on this issue and share with team.
- [ ] Read 1.26 release notes, and focus on breaking changes. Given those findings, work with the leads to determine if this is safe to add support for in Edge 1.14
- [ ] If so, enable our tests to use k8s 1.26 (PRs and weekly tests) on Edge 1.14, and update our support docs to reflect this
- [ ] Update our main branch to use kube 1.26 for tests
- [ ] Update our main branch to use kube 1.26 library

**Comment by inFocus7** [comment]
Although the description brings up doing this for `1.14`, should we first focus on making sure it works with `1.15-beta`/`master`, then look into 1.14?

Also, the work done with bumping to `1.25` encompassed multiple repos [here](https://github.com/solo-io/gloo/issues/6833#issuecomment-1487081447). Is this also a generalized PR meant to get everything on `1.26`?

**Comment by inFocus7** [comment]
# List of repos (to-be-)upgraded to k8s 1.26

## 1.15-beta
- [ ] cloud-builders
- [ ] k8s-utils? (used in both OSS + EE. Is on 1.25, but didn't see it in Jenny's list for 1.25)
- [x] skv2 - _k8s upgraded in v0.30.0_
- [ ] solo-kit? (used into both OSS + EE. Is on 1.25, but didn't see in Jenny's list for 1.25)
- [ ] gloo
- [x] solo-apis - _k8s upgraded in gloo master_ 
- [x] ext-auth-service - _k8s upgraded in v0.36.0_
- [x] rate-limiter - _k8s upgraded in v0.9.0_
- [ ] caching-service
- [x] external-apis - _k8s upgraded in gloo-v0.2.0_
- [ ] solo-projects
	- [x] Update bare-minimum to unblock devs - _k8s upgraded in latest version_
	- [ ] Also update the tests to use kube 1.26
	- [ ] Update the changelog to reflect the correct skv2 version

## 1.14
_TODO_ (will be opening up a quick 1.14 PR to do a quick test if any failures are readily apparent)
