### ISSUE TITLE
Go 1.21 (august) (edge 1.16)

### ISSUE THREAD

**Issue by nfuden** [solo-io/gloo#8474]
### Version

None

### Is your feature request related to a problem? Please describe.

go 1.21 is being released in august and has a critical component change in its modules system
From its changelog 
`To improve forwards compatibility, Go 1.21 now reads the go line in a go.work or go.mod file as a strict minimum requirement: go 1.21.0 means that the workspace or module cannot be used with Go 1.20 or with Go 1.21rc1. This allows projects that depend on fixes made in later versions of Go to ensure that they are not used with earlier versions. It also gives better error reporting for projects that make use of new Go features: when the problem is that a newer Go version is needed, that problem is reported clearly, instead of attempting to build the code and instead printing errors about unresolved imports or syntax errors.
`

As we try to version lock go for an lts branch, so as to not break plugins and avoid potential grpc mismatches (grpc ones is rare), we need to tackle this early

### Describe the solution you'd like

update gloo to go 1.21

```[tasklist]
### Tasks
- [x] Bump our go mod in gloo, solo-apis, solo-projects (enterprise) and run all tests to make sure that functionality is unimpaired
- [ ] Bump go mod version for ext-auth, rate-limiter, and any other dependencies
- [ ] Add build toolchain support in make file so that in the future we dont need to use gvm
```

**Comment by jenshu** [comment]
available in Gloo EE 1.16.0-beta3
